import type { Metadata } from 'next'
import './globals.css'


export const metadata: Metadata = {
    title: 'Universal Link Web App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className='w-full h-screen'>
                {children}
            </body>
        </html>
    )
}
